import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';

/**
 * TermsView Component
 * Terms of Service page
 */
const TermsView = () => {
    return (
        <div className="min-h-screen bg-white font-sans text-slate-800">
            <div className="max-w-3xl mx-auto px-6 py-6">
                <Link to="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-700 font-medium text-sm transition-colors">
                    <ArrowLeft size={16} /> Back to Home
                </Link>
            </div>

            <div className="max-w-3xl mx-auto px-6 pb-20">
                <div className="flex items-center gap-3 mb-8">
                    <div className="w-12 h-12 bg-[#2278B0]/10 rounded-xl flex items-center justify-center">
                        <FileText size={24} className="text-[#2278B0]" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-black text-slate-900">Terms of Service</h1>
                        <p className="text-sm text-slate-500">Last updated: February 2026</p>
                    </div>
                </div>

                <div className="prose prose-slate max-w-none space-y-6">
                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
                        <p className="text-slate-600 leading-relaxed">
                            By accessing and using Evoluter ("the Platform"), you agree to be bound by these Terms of
                            Service. If you do not agree with any part of these terms, you may not use the Platform.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">2. Description of Service</h2>
                        <p className="text-slate-600 leading-relaxed">
                            Evoluter is an AI-powered exam preparation platform that provides personalized test
                            generation, performance analytics, syllabus tracking, and study material management
                            for competitive exam aspirants.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">3. User Accounts</h2>
                        <ul className="list-disc pl-6 space-y-1 text-slate-600">
                            <li>You must provide accurate and complete registration information</li>
                            <li>You are responsible for maintaining the security of your account</li>
                            <li>You must be at least 13 years old to create an account</li>
                            <li>One person may not maintain more than one account</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">4. Acceptable Use</h2>
                        <p className="text-slate-600 leading-relaxed mb-3">You agree not to:</p>
                        <ul className="list-disc pl-6 space-y-1 text-slate-600">
                            <li>Use the Platform for any illegal purpose</li>
                            <li>Upload malicious content or attempt to compromise the system</li>
                            <li>Share your account credentials with others</li>
                            <li>Scrape, crawl, or use automated tools to extract content</li>
                            <li>Redistribute AI-generated content commercially without permission</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">5. Intellectual Property</h2>
                        <p className="text-slate-600 leading-relaxed">
                            All content generated by the Platform, including AI-generated questions, analyses,
                            and feedback, is provided for personal educational use only. The Platform's code,
                            design, and branding are the property of Evoluter and may not be reproduced without
                            permission.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">6. AI-Generated Content Disclaimer</h2>
                        <p className="text-slate-600 leading-relaxed">
                            Questions, analyses, and recommendations generated by our AI system are for educational
                            purposes. While we strive for accuracy, AI-generated content may contain errors. Users
                            should verify important information with official sources and textbooks.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">7. Limitation of Liability</h2>
                        <p className="text-slate-600 leading-relaxed">
                            Evoluter is provided "as is" without warranties of any kind. We are not liable for
                            any damages arising from your use of the Platform, including but not limited to
                            exam results, lost study progress, or data loss.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">8. Modifications</h2>
                        <p className="text-slate-600 leading-relaxed">
                            We reserve the right to modify these Terms at any time. Users will be notified of
                            significant changes via email or in-app notification. Continued use after modifications
                            constitutes acceptance of the updated Terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">9. Contact</h2>
                        <p className="text-slate-600 leading-relaxed">
                            For questions about these Terms, contact us at{' '}
                            <a href="mailto:legal@evoluter.in" className="text-[#2278B0] font-bold hover:underline">
                                legal@evoluter.in
                            </a>.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default TermsView;
